spring.application.name=AyilBank

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:postgresql://localhost:5439/ayilbank_db
spring.datasource.username=postgres
spring.datasource.password=postgres

test.app.secret=g2S9x1nZb6VQ3p7tM8cJ5r2U1wY4l9NkQ0rTeHwXaEo=